# Generated by Django 4.2.2 on 2023-12-09 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
